name: LunityCraft_TopLuck
version: '${version}'
main: fr.lunitycraft.fauza.lunitycraft_topluck.LunityCraft_TopLuck
authors: [FauZaPespi]
commands:
  topluck:
    description: Opens the Top Luck GUI for a specified player.
    permission: LunityCraft.topluck